[package]
name = "sigi"
version = "0.1.3"
authors = ["♪ hiljusti 🎮 <hiljusti@pm.me>"]
edition = "2018"
license = " GPL-3.0-or-later"
description = "Sigi: a prioritization tool"
readme = "README.md"
homepage = "https://github.com/hiljusti/sigi"
repository = "https://github.com/hiljusti/sigi"
documentation = "https://github.com/hiljusti/sigi"
keywords = ["organization", "planning", "stack", "todo", "cli"]
categories = ["command-line-interface", "database-implementations"]

[badges]
maintenance = { status = "experimental" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
clap = "2.33"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

