[package]
name = "sigi"
version = "0.1.0"
authors = ["♪ hiljusti 🎮 <hiljusti@pm.me>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
clap = "2.33"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
